import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const baseQuery = fetchBaseQuery({
  baseUrl: "/api/tmdb",
});

export const mainApiSlice = createApi({
  reducerPath: "mainApi",
  keepUnusedDataFor: 3600,
  baseQuery,
  tagTypes: [
    "Movies",
    "MovieGenres",
    "TVShowsGenres",
    "AllTrends",
    "MoviesTrends",
    "TVShowsTrends",
    "PeopleTrends",
    "TVShows",
    "People",
    "MovieVideos",
    "TVShowVideos",
    "TvShowDetails",
    "MovieDetails",
    "MovieCredits",
    "TvShowCredits",
    "MovieImages",
    "TvShowImages",
    "PersonImages",
    "MovieReviews",
    "TvShowReviews",
    "MovieRecommendations",
    "TvShowRecommendations",
    "MovieSimilars",
    "TvShowSimilars",
    "PersonDetails",
    "TvSeasonDetails",
    "SearchMulti",
    "SearchMovies",
    "SearchTvShows",
    "SearchPeople",
    "NowPlayingMovies",
    "PopularMovies",
    "PopularTvShows",
    "PopularPeople",
    "TopRatedMovies",
    "TopRatedTvShows",
    "UpcomingMovies",
    "AiringToday",
    "OnTheAir",
    "MovieTranslations",
    "TvTranslations",
    "EpisodeTranslations",
  ],

  endpoints: () => ({}),
});
